
package view;

import java.awt.Color;
/**
 *
 * @author ACER
 */
import control.CustomerControl;
import control.EmployeeControl;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Employee;


import table.TableEmployee;


import control.ServiceControl;

import model.Customer;
import model.Service;

import table.TableService;

public class OwnerMainView extends javax.swing.JFrame {
    private EmployeeControl employeeControl;
    private String action;
    private String id, status, posisi, temp1;
    private int temp;
    
    private ServiceControl serviceControl;
    private String action2, jasaAntar, temp2;
    /**
     * Creates new form OwnerMainView
     */
    
    Color defaultcolor, clickedcolor, white, black;
    public OwnerMainView() {
        initComponents();
        //TABLE 1
        setComponent(false);
        idInput.setEnabled(false);
        employeeControl = new EmployeeControl();
        showCustomer();
        clearText();
        
        //TABLE2
        setComponent2(false);
        serviceControl = new ServiceControl();
        showService();
        clearText2();
        defaultcolor = new Color(255,255,204);
        clickedcolor = new Color(51,51,51);
        white = new Color(255,255,255);
        black = new Color(0,0,0); 
    }
    
    public void setComponent(boolean value){
       ubahBtn.setEnabled(value);
       hapusBtn.setEnabled(value);
      
       namaInput.setEnabled(value);
       telpInput.setEnabled(value);
       passInput.setEnabled(value);
       statusDd.setEnabled(value);
       jabatanDd.setEnabled(value);
       
       jButton2.setEnabled(value);
       jButton1.setEnabled(value);
    }
    
    public void setComponent2(boolean value){
       idInput1.setEnabled(value);
       ubahBtn1.setEnabled(value);
       hapusBtn1.setEnabled(value);
       namaInput1.setEnabled(value);
       kecepatanInput.setEnabled(value);
       biayaInput.setEnabled(value);
       yesRadBtn.setEnabled(value);
       noRadBtn.setSelected(value);
       yesRadBtn.setSelected(value);
       noRadBtn.setSelected(value); 
       jButton4.setEnabled(value);
       jButton3.setEnabled(value);
    }
    
     public void clearText(){
        namaInput.setText("");
        telpInput.setText("");
        passInput.setText("");
        idInput.setText("");
        cariInput.setText("");
    }
     
    public void clearText2(){
        namaInput1.setText("");
        kecepatanInput.setText("");
        biayaInput.setText("");
        idInput1.setText("");
        yesRadBtn.setSelected(false);
        noRadBtn.setSelected(false); 
        
    }
     
    public void showCustomer(){
        jTable1.setModel(employeeControl.showDataEmployee());
    }
    
    public void showService(){
        jTable2.setModel(serviceControl.showDataService());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesNoGroup = new javax.swing.ButtonGroup();
        judulPanel = new javax.swing.JPanel();
        ownerLabel = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        karyawanPanel = new javax.swing.JPanel();
        tklabel = new javax.swing.JLabel();
        karyawanIcons = new javax.swing.JLabel();
        layananPanel = new javax.swing.JPanel();
        tllabel = new javax.swing.JLabel();
        layananIcons = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelKaryawan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        containerPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        telpNama = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jabatanLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        namaInput = new javax.swing.JTextField();
        passInput = new javax.swing.JTextField();
        telpInput = new javax.swing.JTextField();
        statusDd = new javax.swing.JComboBox<>();
        jabatanDd = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cariInput = new javax.swing.JTextField();
        cariBtn = new javax.swing.JButton();
        tambahBtn = new javax.swing.JButton();
        ubahBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        judulLabel = new javax.swing.JLabel();
        panelLayanan = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        judulLabel1 = new javax.swing.JLabel();
        cariBtn1 = new javax.swing.JButton();
        cariInput1 = new javax.swing.JTextField();
        tambahBtn1 = new javax.swing.JButton();
        ubahBtn1 = new javax.swing.JButton();
        hapusBtn1 = new javax.swing.JButton();
        containerPanel1 = new javax.swing.JPanel();
        idLabel1 = new javax.swing.JLabel();
        namaLabel1 = new javax.swing.JLabel();
        kecepatanLabel = new javax.swing.JLabel();
        biayaLabel = new javax.swing.JLabel();
        jasaLabel = new javax.swing.JLabel();
        idInput1 = new javax.swing.JTextField();
        namaInput1 = new javax.swing.JTextField();
        kecepatanInput = new javax.swing.JTextField();
        biayaInput = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        yesRadBtn = new javax.swing.JRadioButton();
        noRadBtn = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judulPanel.setBackground(new java.awt.Color(0, 0, 0));

        ownerLabel.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        ownerLabel.setForeground(new java.awt.Color(255, 255, 255));
        ownerLabel.setText("OWNER");

        javax.swing.GroupLayout judulPanelLayout = new javax.swing.GroupLayout(judulPanel);
        judulPanel.setLayout(judulPanelLayout);
        judulPanelLayout.setHorizontalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ownerLabel)
                .addContainerGap(973, Short.MAX_VALUE))
        );
        judulPanelLayout.setVerticalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judulPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ownerLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(judulPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 80));

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 204));

        karyawanPanel.setBackground(new java.awt.Color(255, 255, 204));

        tklabel.setBackground(new java.awt.Color(255, 255, 204));
        tklabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        tklabel.setForeground(new java.awt.Color(0, 0, 0));
        tklabel.setText("Tambah Karyawan");
        tklabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tklabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tklabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tklabelMouseReleased(evt);
            }
        });

        karyawanIcons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customer.png"))); // NOI18N

        javax.swing.GroupLayout karyawanPanelLayout = new javax.swing.GroupLayout(karyawanPanel);
        karyawanPanel.setLayout(karyawanPanelLayout);
        karyawanPanelLayout.setHorizontalGroup(
            karyawanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, karyawanPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tklabel)
                .addGap(19, 19, 19))
            .addGroup(karyawanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(karyawanIcons)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        karyawanPanelLayout.setVerticalGroup(
            karyawanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, karyawanPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(karyawanIcons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tklabel)
                .addContainerGap())
        );

        layananPanel.setBackground(new java.awt.Color(255, 255, 204));

        tllabel.setBackground(new java.awt.Color(255, 255, 204));
        tllabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        tllabel.setForeground(new java.awt.Color(0, 0, 0));
        tllabel.setText("Tambah Layanan");
        tllabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tllabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tllabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tllabelMouseReleased(evt);
            }
        });

        layananIcons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addLayanan-icons.png"))); // NOI18N

        javax.swing.GroupLayout layananPanelLayout = new javax.swing.GroupLayout(layananPanel);
        layananPanel.setLayout(layananPanelLayout);
        layananPanelLayout.setHorizontalGroup(
            layananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layananPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tllabel)
                    .addComponent(layananIcons))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layananPanelLayout.setVerticalGroup(
            layananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layananPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layananIcons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tllabel)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(karyawanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(layananPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(karyawanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(layananPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        getContentPane().add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 630));

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(55, 121, 164));

        containerPanel.setBackground(new java.awt.Color(255, 255, 255));

        idLabel.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 0, 0));
        idLabel.setText("ID");

        namaLabel.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaLabel.setText("Nama Karyawan");

        passLabel.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        passLabel.setForeground(new java.awt.Color(0, 0, 0));
        passLabel.setText("Password");

        telpNama.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        telpNama.setForeground(new java.awt.Color(0, 0, 0));
        telpNama.setText("Nomor Telepon");

        statusLabel.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(0, 0, 0));
        statusLabel.setText("Status");

        jabatanLabel.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jabatanLabel.setForeground(new java.awt.Color(0, 0, 0));
        jabatanLabel.setText("Jabatan");

        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });

        statusDd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));
        statusDd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusDdActionPerformed(evt);
            }
        });

        jabatanDd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senior", "Junior" }));
        jabatanDd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanDdActionPerformed(evt);
            }
        });

        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jabatanLabel)
                            .addComponent(statusLabel)
                            .addComponent(telpNama)
                            .addComponent(passLabel)
                            .addComponent(idLabel)
                            .addComponent(namaLabel)
                            .addComponent(namaInput)
                            .addComponent(idInput)
                            .addComponent(passInput)
                            .addComponent(telpInput)
                            .addComponent(statusDd, 0, 252, Short.MAX_VALUE)
                            .addComponent(jabatanDd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jButton1)
                .addContainerGap())
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaLabel)
                .addGap(3, 3, 3)
                .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telpNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusDd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jabatanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jabatanDd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(16, 16, 16))
        );

        cariInput.setBackground(new java.awt.Color(255, 255, 255));
        cariInput.setForeground(new java.awt.Color(0, 0, 0));
        cariInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariInputActionPerformed(evt);
            }
        });

        cariBtn.setBackground(new java.awt.Color(255, 255, 255));
        cariBtn.setForeground(new java.awt.Color(0, 0, 0));
        cariBtn.setText("Cari");
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });

        tambahBtn.setBackground(new java.awt.Color(255, 255, 255));
        tambahBtn.setForeground(new java.awt.Color(0, 0, 0));
        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        ubahBtn.setBackground(new java.awt.Color(255, 255, 255));
        ubahBtn.setForeground(new java.awt.Color(0, 0, 0));
        ubahBtn.setText("Ubah");
        ubahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahBtnActionPerformed(evt);
            }
        });

        hapusBtn.setBackground(new java.awt.Color(255, 255, 255));
        hapusBtn.setForeground(new java.awt.Color(0, 0, 0));
        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        judulLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        judulLabel.setForeground(new java.awt.Color(255, 255, 255));
        judulLabel.setText("Tambah Karyawan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cariBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariInput, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tambahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(ubahBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusBtn))
                    .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(judulLabel)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBtn))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBtn)
                    .addComponent(ubahBtn)
                    .addComponent(hapusBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout panelKaryawanLayout = new javax.swing.GroupLayout(panelKaryawan);
        panelKaryawan.setLayout(panelKaryawanLayout);
        panelKaryawanLayout.setHorizontalGroup(
            panelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        panelKaryawanLayout.setVerticalGroup(
            panelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKaryawanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", panelKaryawan);

        jPanel2.setBackground(new java.awt.Color(55, 121, 164));

        judulLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        judulLabel1.setForeground(new java.awt.Color(255, 255, 255));
        judulLabel1.setText("Tambah Layanan");

        cariBtn1.setBackground(new java.awt.Color(255, 255, 255));
        cariBtn1.setForeground(new java.awt.Color(0, 0, 0));
        cariBtn1.setText("Cari");
        cariBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtn1ActionPerformed(evt);
            }
        });

        cariInput1.setBackground(new java.awt.Color(255, 255, 255));
        cariInput1.setForeground(new java.awt.Color(0, 0, 0));
        cariInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariInput1ActionPerformed(evt);
            }
        });

        tambahBtn1.setBackground(new java.awt.Color(255, 255, 255));
        tambahBtn1.setForeground(new java.awt.Color(0, 0, 0));
        tambahBtn1.setText("Tambah");
        tambahBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtn1ActionPerformed(evt);
            }
        });

        ubahBtn1.setBackground(new java.awt.Color(255, 255, 255));
        ubahBtn1.setForeground(new java.awt.Color(0, 0, 0));
        ubahBtn1.setText("Ubah");
        ubahBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahBtn1ActionPerformed(evt);
            }
        });

        hapusBtn1.setBackground(new java.awt.Color(255, 255, 255));
        hapusBtn1.setForeground(new java.awt.Color(0, 0, 0));
        hapusBtn1.setText("Hapus");
        hapusBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtn1ActionPerformed(evt);
            }
        });

        containerPanel1.setBackground(new java.awt.Color(255, 255, 255));

        idLabel1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        idLabel1.setForeground(new java.awt.Color(0, 0, 0));
        idLabel1.setText("ID");

        namaLabel1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        namaLabel1.setForeground(new java.awt.Color(0, 0, 0));
        namaLabel1.setText("Nama ");

        kecepatanLabel.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        kecepatanLabel.setForeground(new java.awt.Color(0, 0, 0));
        kecepatanLabel.setText("Kecepatan");

        biayaLabel.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        biayaLabel.setForeground(new java.awt.Color(0, 0, 0));
        biayaLabel.setText("Biaya");

        jasaLabel.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jasaLabel.setForeground(new java.awt.Color(0, 0, 0));
        jasaLabel.setText("Jasa Antar");

        idInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInput1ActionPerformed(evt);
            }
        });

        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Simpan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        yesNoGroup.add(yesRadBtn);
        yesRadBtn.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        yesRadBtn.setForeground(new java.awt.Color(0, 0, 0));
        yesRadBtn.setText("Yes");
        yesRadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRadBtnActionPerformed(evt);
            }
        });

        yesNoGroup.add(noRadBtn);
        noRadBtn.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        noRadBtn.setForeground(new java.awt.Color(0, 0, 0));
        noRadBtn.setText("No");
        noRadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRadBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerPanel1Layout = new javax.swing.GroupLayout(containerPanel1);
        containerPanel1.setLayout(containerPanel1Layout);
        containerPanel1Layout.setHorizontalGroup(
            containerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanel1Layout.createSequentialGroup()
                .addGroup(containerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(containerPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(containerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yesRadBtn)
                            .addGroup(containerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jasaLabel)
                                .addComponent(biayaLabel)
                                .addComponent(kecepatanLabel)
                                .addComponent(idLabel1)
                                .addComponent(namaLabel1)
                                .addComponent(namaInput1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                .addComponent(idInput1)
                                .addComponent(kecepatanInput)
                                .addComponent(biayaInput))
                            .addComponent(noRadBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)))
                .addComponent(jButton3)
                .addContainerGap())
        );
        containerPanel1Layout.setVerticalGroup(
            containerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(idLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaLabel1)
                .addGap(3, 3, 3)
                .addComponent(namaInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kecepatanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kecepatanInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biayaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biayaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jasaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yesRadBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noRadBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(containerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(16, 16, 16))
        );

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(containerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cariBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tambahBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(ubahBtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusBtn1))
                    .addComponent(judulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(judulLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBtn1))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBtn1)
                    .addComponent(ubahBtn1)
                    .addComponent(hapusBtn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(containerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel2);

        javax.swing.GroupLayout panelLayananLayout = new javax.swing.GroupLayout(panelLayanan);
        panelLayanan.setLayout(panelLayananLayout);
        panelLayananLayout.setHorizontalGroup(
            panelLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        panelLayananLayout.setVerticalGroup(
            panelLayananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", panelLayanan);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 970, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void tklabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tklabelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_tklabelMouseClicked

    private void tklabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tklabelMousePressed
        // TODO add your handling code here:
        karyawanPanel.setBackground(clickedcolor);
        layananPanel.setBackground(defaultcolor);
        tklabel.setForeground(white);
    }//GEN-LAST:event_tklabelMousePressed

    private void tklabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tklabelMouseReleased
        // TODO add your handling code here:
        karyawanPanel.setBackground(defaultcolor);
        tklabel.setForeground(black);
    }//GEN-LAST:event_tklabelMouseReleased

    private void cariInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariInputActionPerformed

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        
    }//GEN-LAST:event_idInputActionPerformed

    private void cariInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariInput1ActionPerformed

    private void idInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInput1ActionPerformed

    private void tllabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tllabelMouseReleased
        // TODO add your handling code here:
        layananPanel.setBackground(defaultcolor);
        tllabel.setForeground(black);
    }//GEN-LAST:event_tllabelMouseReleased

    private void tllabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tllabelMousePressed
        // TODO add your handling code here:
        karyawanPanel.setBackground(defaultcolor);
        layananPanel.setBackground(clickedcolor);
        tllabel.setForeground(white);
    }//GEN-LAST:event_tllabelMousePressed

    private void tllabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tllabelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_tllabelMouseClicked

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        setComponent(false);
        
        try{
           TableEmployee employee = employeeControl.showDataBySearch(cariInput.getText());
            if(employee.getRowCount() == 0){
                clearText();
                ubahBtn.setEnabled(false);
                hapusBtn.setEnabled(false);
                JOptionPane.showConfirmDialog(rootPane, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                jTable1.setModel(employee);
            }
        }catch(Exception e){
            System.out.println("Error : "+e.getMessage());
        }
    }//GEN-LAST:event_cariBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Apakah yaking ingin menghapus data ? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        switch(getAnswer){
            case 0:
                try{
                    employeeControl.deleteDataEmployee(idInput.getText());
                    clearText();
                    showCustomer();
                    setComponent(false);
                }catch(Exception e){
                    System.out.println("Error : "+e.getMessage());
                }
                break;
            case 1:
                break;
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void ubahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahBtnActionPerformed
        setComponent(true);
        action = "Ubah";
        tambahBtn.setEnabled(false);
        hapusBtn.setEnabled(false);
    }//GEN-LAST:event_ubahBtnActionPerformed

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        setComponent(true);
        ubahBtn.setEnabled(false);
        hapusBtn.setEnabled(false);
        clearText();
        cariInput.setText("");
        id = employeeControl.generateIDKaryawan();
        idInput.setText(id);
        action = "Tambah";
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
           temp = statusDd.getSelectedIndex();
           switch(temp){
               case 0:
                   status = "Aktif";
                   break;
               case 1:
                   status = "Tidak Aktif";
                   break;
           }
           temp = jabatanDd.getSelectedIndex();
           switch(temp){
               case 0:
                   posisi = "Senior";
                   break;
               case 1:
                   posisi = "Junior";
                   break;
           }
            Employee e = new Employee(idInput.getText(), namaInput.getText(), passInput.getText(), Integer.parseInt(telpInput.getText()), status, posisi);
           
            if(action.equals("Tambah")){
                employeeControl.insertDataEmployee(e);
            }else{
                employeeControl.updateDataEmployee(e, idInput.getText());
            }
            clearText();
            showCustomer();
            setComponent(false);
        }catch (Exception e){
            System.out.println("Gagal menyimpan data");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setComponent(false);
        clearText();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        setComponent(false);
        ubahBtn.setEnabled(true);
        hapusBtn.setEnabled(true);
        
        int clickedRow = jTable1.getSelectedRow();
        TableModel table = jTable1.getModel();
        
        
        idInput.setText(table.getValueAt(clickedRow, 0).toString());
        namaInput.setText(table.getValueAt(clickedRow, 1).toString());
        passInput.setText(table.getValueAt(clickedRow, 2).toString());
        telpInput.setText(table.getValueAt(clickedRow, 3).toString());
        temp1 = table.getValueAt(clickedRow, 4).toString();
        
        if(temp1.equalsIgnoreCase("Aktif")){
            statusDd.setSelectedIndex(0);
        }else{
            statusDd.setSelectedIndex(1);
        }
        
        temp1 = table.getValueAt(clickedRow, 5).toString();
        
        if(temp1.equalsIgnoreCase("Kurir")){
            jabatanDd.setSelectedIndex(1);
        }else{
            jabatanDd.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void yesRadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRadBtnActionPerformed
        jasaAntar = "Ya";
    }//GEN-LAST:event_yesRadBtnActionPerformed

    private void noRadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRadBtnActionPerformed
        jasaAntar = "Tidak";
    }//GEN-LAST:event_noRadBtnActionPerformed

    private void ubahBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahBtn1ActionPerformed
       setComponent2(true);
        action2 = "Ubah";
    }//GEN-LAST:event_ubahBtn1ActionPerformed

    private void tambahBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtn1ActionPerformed
        setComponent2(true);
        ubahBtn1.setEnabled(false);
        hapusBtn1.setEnabled(false);
        clearText2();
        cariInput1.setText("");
        action2 = "Tambah";
        jasaAntar = "Tidak";
    }//GEN-LAST:event_tambahBtn1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Service s = new Service(idInput1.getText(), namaInput1.getText(), Integer.parseInt(kecepatanInput.getText()), jasaAntar, Integer.parseInt(biayaInput.getText()));
           
            if(action2.equals("Tambah")){
                serviceControl.insertDataService(s);
            }else{
                serviceControl.updateDataService(s, idInput1.getText());
            }
            clearText2();
            showService();
            setComponent2(false);
        }catch (Exception e){
            System.out.println("Gagal menyimpan data");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setComponent2(false);
        clearText2();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cariBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtn1ActionPerformed
        setComponent2(false);
         try{
           TableService service = serviceControl.showDataBySearch(cariInput1.getText());
            if(service.getRowCount() == 0){
                clearText2();
                ubahBtn1.setEnabled(false);
                hapusBtn1.setEnabled(false);
                JOptionPane.showConfirmDialog(rootPane, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                jTable2.setModel(service);
            }
        }catch(Exception e){
            System.out.println("Error : "+e.getMessage());
        }
        
    }//GEN-LAST:event_cariBtn1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        setComponent2(false);
        ubahBtn1.setEnabled(true);
        hapusBtn1.setEnabled(true);
        
        int clickedRow = jTable2.getSelectedRow();
        TableModel table = jTable2.getModel();
        
        
        idInput1.setText(table.getValueAt(clickedRow, 0).toString());
        namaInput1.setText(table.getValueAt(clickedRow, 1).toString());
        kecepatanInput.setText(table.getValueAt(clickedRow, 2).toString());
        temp2 = table.getValueAt(clickedRow, 3).toString();
        if(temp2.equalsIgnoreCase("Ya")){
            yesRadBtn.setSelected(true);
            noRadBtn.setSelected(false);
            jasaAntar = "Ya";
        }else{
            yesRadBtn.setSelected(false);
            noRadBtn.setSelected(true);
            jasaAntar = "Tidak";
        }
        biayaInput.setText(table.getValueAt(clickedRow, 4).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void hapusBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtn1ActionPerformed
       int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Apakah yaking ingin menghapus data ? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        switch(getAnswer){
            case 0:
                try{
                    serviceControl.deleteDataService(idInput.getText());
                    
                    clearText2();
                    showService();
                    setComponent2(false);
                }catch(Exception e){
                    System.out.println("Error : "+e.getMessage());
                }
                break;
            case 1:
                break;
        }
    }//GEN-LAST:event_hapusBtn1ActionPerformed

    private void jabatanDdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanDdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatanDdActionPerformed

    private void statusDdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusDdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusDdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnerMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnerMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnerMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnerMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OwnerMainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biayaInput;
    private javax.swing.JLabel biayaLabel;
    private javax.swing.JButton cariBtn;
    private javax.swing.JButton cariBtn1;
    private javax.swing.JTextField cariInput;
    private javax.swing.JTextField cariInput1;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel containerPanel1;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JButton hapusBtn1;
    private javax.swing.JTextField idInput;
    private javax.swing.JTextField idInput1;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> jabatanDd;
    private javax.swing.JLabel jabatanLabel;
    private javax.swing.JLabel jasaLabel;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JLabel judulLabel1;
    private javax.swing.JPanel judulPanel;
    private javax.swing.JLabel karyawanIcons;
    private javax.swing.JPanel karyawanPanel;
    private javax.swing.JTextField kecepatanInput;
    private javax.swing.JLabel kecepatanLabel;
    private javax.swing.JLabel layananIcons;
    private javax.swing.JPanel layananPanel;
    private javax.swing.JTextField namaInput;
    private javax.swing.JTextField namaInput1;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaLabel1;
    private javax.swing.JRadioButton noRadBtn;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JPanel panelKaryawan;
    private javax.swing.JPanel panelLayanan;
    private javax.swing.JTextField passInput;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JComboBox<String> statusDd;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton tambahBtn1;
    private javax.swing.JTextField telpInput;
    private javax.swing.JLabel telpNama;
    private javax.swing.JLabel tklabel;
    private javax.swing.JLabel tllabel;
    private javax.swing.JButton ubahBtn;
    private javax.swing.JButton ubahBtn1;
    private javax.swing.ButtonGroup yesNoGroup;
    private javax.swing.JRadioButton yesRadBtn;
    // End of variables declaration//GEN-END:variables
}
